log:
  level: error
  file: ""

include: []

plugins:
  - tag: cache
    type: cache
    args:
      size: 1500
      lazy_cache_ttl: 86400
      dump_file: /etc/mosdns/cache.dump
      dump_interval: 600

  - tag: forward
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: dnspod-doh
          addr: https://doh.pub/dns-query
          dial_addr: "1.12.12.12"
          bootstrap: "223.5.5.5"
        - tag: alidns
          addr: tls://dns.alidns.com
          dial_addr: "223.5.5.5"
          bootstrap: "119.29.29.29"
          enable_pipeline: true

  - tag: reverse_lookup
    type: reverse_lookup
    args:
      size: 65535 # 内置缓存大小。默认 65535。
      
      # 缓存时间。秒。默认 7200 (2h)。应答记录的 TTL 也会被自动修改，限制在该值以下。
      ttl: 7200
      # 是否主动处理/响应 PTR 请求。如果 PTR 的 IP 命中缓存，则生成应答。
      # 该功能的一个用途是，当下游设备使用网络监视类工具查看网络连接时，开启域名反查功能大概率会看到 IP 对应的
      # 真实域名(如果程序先请求域名再建立连接，而且域名经过了该插件处理。)
      handle_ptr: true

  - tag: remote
    type: sequence
    args:
      - exec: $forward
  
  - tag: local
    type: sequence
    args:
      - exec: forward 192.168.1.1:53

  - tag: main_sequence
    type: sequence
    args:
      - exec: query_summary
      - exec: $reverse_lookup
      - exec: $cache
      - matches:
        - "!qname domain:.lan"
        exec: $remote
      - matches: has_resp
        exec: accept
      - exec: $local

  - type: udp_server
    args:
      entry: main_sequence
      listen: :6052
  
  - type: tcp_server
    args:
      entry: main_sequence
      listen: :6052
